[project]
name = "compiled"
version = "0.2.1"
description = "Compiled versions of the stdlib."
# TODO: Add README
authors = [
    {name = "Tushar Sadhwani", email = "tushar.sadhwani000@gmail.com"},
]
# TODO: bump this down
requires-python = ">=3.11"

[project.urls]
Homepage = "https://github.com/tusharsadhwani/compiled"

[project.scripts]
pycompile = "compiled:cli"

[build-system]
requires = [
    "setuptools",
    "wheel",
    "mypy[mypyc]",
]
build-backend = "setuptools.build_meta"
