name: Build compiled package

on:
  workflow_dispatch:
  push:
    branches:
    - 'compiled-3.11'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.builds.os }}
    strategy:
      fail-fast: false
      matrix:
        builds: [
          {os: "macos-latest"},
          {os: "windows-latest"},
          {os: "ubuntu-latest"}
        ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install deps
        run: python -m pip install mypy[mypyc] twine
      - name: Build wheels
        run: python build.py package
      # - name: Publish
      #   env:
      #     TWINE_USERNAME: __token__
      #     TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      #   run: |
      #     twine upload --skip-existing wheelhouse/*
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.builds.os }}
          path: ./build/dist/*.whl
